# -*- coding: utf-8 -*-
"""Python Quiz

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qpCDSRbAdfx20titXrtkB2LuGF5j2lqI

# Create a DataFrame from a dictionary of lists
"""

import pandas as pd

"""### init a dataframe by dict with different index"""

d = {"a": {"a1":1, "a2":2, "c":3}, "b":{"b1":2, "b2":4, "c":9}}
df = pd.DataFrame(d)

print("The DataFrame")
print(df)