# -*- coding: utf-8 -*-
"""Python Quiz

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qpCDSRbAdfx20titXrtkB2LuGF5j2lqI

# Creating a DataFrame using a NumPy array
"""

import pandas as pd
import numpy as np

d = np.random.normal(size=(2,3))
print("The original Numpy array")
print(d)
print('------------------------------------')

s = pd.DataFrame(d)
print("The DataFrame ")
print(s)