# -*- coding: utf-8 -*-
"""Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kgmxMppOf6Fdnsk0tgO0yIENtdDQntM4

# Functions

### Examples of build-in functions
"""

x = [0,2,3,4,5,7,8,900,12]

max(x)

len(x)

round(1.557, 2)

round(1.55)

sorted(x, reverse=True)



"""#### sum() and round() function"""

num_list = [4,3,5,6]
print(sum(num_list))

# round(number, numberofdecimal)
round(1.68, 1)