# -*- coding: utf-8 -*-
"""Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kgmxMppOf6Fdnsk0tgO0yIENtdDQntM4

# Dictionaties
"""

d = {}
# Declaring an empty dictionaty. You can also define as : d = dict{}
#Example: d = {"George": 24, "Tom": 32, "Ashly": 18}

d["George"] = 24
d["Tom"] = 32
d["Ashly"] = 18

print("Tom is ", d["Tom"])
print("Ashly is ", d["Ashly"])
print("George is ", d["George"])

"""## How to iterate over key-value pairs"""

for key, value in d.items():
  print("Key:")
  print(key)
  print("Value:")
  print(value)
  print("")