# -*- coding: utf-8 -*-
"""Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kgmxMppOf6Fdnsk0tgO0yIENtdDQntM4

# Range()

### Using only one argument
"""

for i in range(5):
  print(i , end=', ')

"""### Using two arguments (i.e., start and stop)"""

for i in range(5, 10):
  print(i, end=', ')

"""### Using all three arguments"""

for i in range(0, 20, 2):
  print(i, end=', ')