# -*- coding: utf-8 -*-
"""Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kgmxMppOf6Fdnsk0tgO0yIENtdDQntM4

# Loops

## For loop
"""

heights = [1.55,1.76,1.80,1.77]
for height in heights:
  print(height)

"""### loop through string"""

for i in 'apple':
  print(i.capitalize())

"""### Enumerate"""

for index,height in enumerate(heights):
    print("index " + str(index) + " = " + str(height))