# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kgmxMppOf6Fdnsk0tgO0yIENtdDQntM4

# Python List methods

## .append()
"""

a = "Hello Cutie"
# type(a)
print(a[-3:-1])

orders = ['smart watch', 'omen keyboard']
orders

orders.append('table light')
orders

"""## Count()"""

locker = ['pen','pencil','textbook','highlighter','notebooks', 'pencil', 'pencil']

numPencil = locker.count('pencil')
print(numPencil)

"""## len()"""

Epl_Clubs = ['Spurs', 'ManCity', 'Liverpool', 'Chelsea','Wolves']
print(len(Epl_Clubs))

"""## .Sorts()"""

num = [2,4,6,8,0,3,5,7,1,2,2,12,46,134]

num.sort()

print(num)